media:
  input: images
  output: /images
  path: images
  categories: [image]
content:

  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields: [permalink, meta_title, header_text]
      primary: meta_title
      sort: [meta_title]
    fields:
      - { name: layout, type: string, label: Layout }
      - { name: permalink, type: string, label: Permalink }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: no_index, type: boolean, label: No Index }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string, label: Key }
          - { name: order, type: number, label: Order }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - name: blocks
        label: Blocks
        type: object
        list: true
        fields:
          - { name: type, type: string, label: Block Type }
          - { name: title, type: string, label: Title }
          - { name: full_width, type: boolean, label: Full Width }
          - { name: class, type: string, label: CSS Class }
          - { name: section_class, type: string, label: Section Class }
          - { name: lead, type: string, label: Lead Text }
          - name: buttons
            label: Buttons
            type: object
            list: true
            fields:
              - { name: text, type: string, label: Text }
              - { name: href, type: string, label: URL }
              - { name: variant, type: string, label: Variant }
              - { name: size, type: string, label: Size }
          - { name: header_title, type: string, label: Header Title }
          - { name: header_subtitle, type: string, label: Header Subtitle }
          - { name: grid_class, type: string, label: Grid Class }
          - { name: heading_level, type: number, label: Heading Level }
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - { name: icon, type: string, label: Icon }
              - { name: title, type: string, label: Title }
              - { name: description, type: string, label: Description }
              - { name: value, type: string, label: Value }
              - { name: label, type: string, label: Label }
          - { name: content, type: code, label: Content, options: { language: markdown } }
          - { name: reverse, type: boolean, label: Reverse Layout }
          - name: button
            label: Button
            type: object
            fields:
              - { name: text, type: string, label: Text }
              - { name: href, type: string, label: URL }
              - { name: variant, type: string, label: Variant }
              - { name: size, type: string, label: Size }
          - { name: figure_type, type: string, label: Figure Type }
          - { name: figure_html, type: code, label: Figure HTML, options: { language: html } }
          - { name: variant, type: string, label: Variant }
          - { name: left_title, type: string, label: Left Title }
          - { name: left_content, type: code, label: Left Content, options: { language: markdown } }
          - { name: right_title, type: string, label: Right Title }
          - { name: right_content, type: code, label: Right Content, options: { language: markdown } }
          - { name: description, type: string, label: Description }

  - name: site
    label: Site Configuration
    type: file
    path: _data/site.json
    fields:
      - { name: name, type: string, label: Site Name }
      - { name: url, type: string, label: Site URL }
      - { name: description, type: string, label: Site Description }
      - name: opening_times
        label: Opening Times
        type: object
        list: true
        fields:
          - { name: day, type: string, label: Day, required: true }
          - { name: hours, type: string, label: Hours, required: true }
      - name: socials
        label: Social Media Links
        type: object
        fields:
          - { name: Facebook, type: string, label: Facebook }
          - { name: Instagram, type: string, label: Instagram }
          - { name: TikTok, type: string, label: TikTok }
          - { name: Google, type: string, label: Google }
          - { name: WhatsApp, type: string, label: WhatsApp }
          - { name: RSS, type: string, label: RSS }

  - name: meta
    label: Meta Configuration
    type: file
    path: _data/meta.json
    fields:
      - { name: language, type: string, label: Language Code, default: "en-GB" }
      - name: organization
        label: Organization
        type: object
        fields:
          - { name: description, type: string, label: Organization Description }
          - { name: legalName, type: string, label: Legal Name }
          - { name: foundingDate, type: string, label: Founding Date }
          - name: founders
            label: Founders
            type: object
            list: true
            fields:
              - { name: name, type: string, label: Name }
          - name: address
            label: Address
            type: object
            fields:
              - { name: streetAddress, type: string, label: Street Address }
              - { name: addressLocality, type: string, label: City }
              - { name: addressRegion, type: string, label: Region/State }
              - { name: postalCode, type: string, label: Postal Code }
              - { name: addressCountry, type: string, label: Country Code }
          - name: contactPoint
            label: Contact Points
            type: object
            list: true
            fields:
              - { name: telephone, type: string, label: Telephone }
              - { name: contactType, type: string, label: Contact Type }
              - { name: areaServed, type: string, label: Area Served }
              - { name: availableLanguage, type: string, label: Available Languages, list: true }
